require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_KEY
);

function extractDomain(url) {
  try { return new URL(url).hostname.replace('www.', ''); } catch { return ''; }
}

function companyFromDomain(url) {
  try {
    const host = new URL(url).hostname.replace('www.', '');
    return host.split('.')[0];
  } catch { return 'historical_import'; }
}

const historicalLeads = [
  { website: 'https://www.agmwindows.net/', email: 'quotes@agmwindows.net', email1_subject: 'the one category most local suppliers miss', email1_body: "you design, install and manufacture custom systems with 20+ years experience. you're likely quoting jobs where clients ask for motorised options, then scrambling to find reliable supply.", email2_subject: 'did this land?', email2_body: 'flagged something on motorised supply for AGM Windows & Doors earlier this week. no urgency, just thought it might close a gap you\'re seeing on custom builds.', email3_subject: 'something about custom spec jobs', email3_body: "most fabricators we work with in your area hit the same wall: clients want integrated motorised systems across bi-folds, sliders, and frameless installs.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read for custom fabricators like AGM, having one source for motorised systems.", email5_subject: 'last one from me', email5_body: "last ping on motorised supply for AGM Windows & Doors. my guess is you haven't replied because: 1. you've already got motorised supply sorted." },
  { website: 'http://wawaluminium.com/', email: 'info@wawaluminium.com.au', email1_subject: 're: your wetherill park installs', email1_body: "you supply and install across western sydney with a focus on residential and commercial projects. most installers we work with quote jobs around louvres, shop fronts and bi-folds.", email2_subject: 'still worth a look?', email2_body: "dropped a note about supply lead times for Wide Aluminium Windows & Doors a few days back. covers motorised systems and direct pricing on the products you already quote.", email3_subject: 'something about wetherill park suppliers', email3_body: "most installers working out of wetherill park and across parramatta are quoting residential bi-folds, security doors and shop fronts but waiting weeks for stock.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting residential and commercial installs across western sydney.", email5_subject: 'last one from me', email5_body: "last ping on direct-source supply for Wide Aluminium Windows & Doors. my guess is you haven't replied because: 1. you've got existing suppliers and the pricing works well." },
  { website: 'https://www.alikaaluminium.com.au/', email: 'info@alikaaluminium.com.au', email1_subject: 'something most sydney installers can\'t get yet', email1_body: "you install across sydney with 12+ years under your belt. you're quoting sliding systems and custom installations, but lead times stretch when suppliers can't stock what clients are starting to ask for.", email2_subject: 'did this land?', email2_body: "dropped a note about supply gaps for Alika Aluminium a few days back. we're direct-source and carry motorised systems most AU suppliers skip.", email3_subject: 're: your sydney install base', email3_body: "you've built 12+ years of client trust installing across sydney, but when a homeowner asks for motorised systems on their renovation and you can't source them locally.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting jobs where clients want motorised systems and your current suppliers.", email5_subject: 'last one from me', email5_body: "last ping for Alika Aluminium on motorised system supply. my guess is you haven't replied because: 1. current suppliers are fine for now and you're not actively looking." },
  { website: 'https://aluminiumwindowsanddoors.net.au/', email: 'quotes@innovativeag.com.au', email1_subject: 'something most sydney installers miss', email1_body: "you handle installs across sydney and surrounding areas. you're covering bi-folds, sliders, double hung, louvres — pretty much the full range of residential product.", email2_subject: 'did this land?', email2_body: "left a note with Innovative Aluminium & Glass about supply consistency recently. covers motorised systems most local suppliers don't stock.", email3_subject: 're: your sydney projects', email3_body: "most fabricators we talk to across sydney are quoting residential and commercial work but turning down jobs that need motorised systems because their current suppliers can't source them reliably.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if keeping your full product range in stock without the usual lead time gaps matters.", email5_subject: 'last one from me', email5_body: "final note for Innovative Aluminium & Glass on supply consistency and product range. my guess is you haven't replied because: 1. your current suppliers are working fine." },
  { website: 'https://www.mtwindow.com.au/', email: 'admin@mtwindow.com.au' },
  { website: 'http://ecoaluminium.com.au/', email: 'info@ecoaluminium.com.au', email1_subject: 'something most sydney fabricators miss', email1_body: "you fabricate and install custom aluminium facades and security systems across sydney. you're building curtain walls and custom facades for projects like prince edward ave and crowsnest.", email2_subject: 'did this land?', email2_body: "left a note with Eco Aluminium about supply consistency on facade projects recently. covers motorised systems most sydney suppliers don't stock.", email3_subject: 're: your earlwood projects', email3_body: "most sydney fabricators running curtain wall and facade jobs in suburbs like earlwood and crowsnest end up managing three or four different suppliers just to cover windows, doors, and security systems.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're quoting facade systems and want to see what motorised options look like.", email5_subject: 'last one from me', email5_body: "last ping for Eco Aluminium on supply consistency for facade builds. my guess is you haven't replied because: 1. you've already got reliable suppliers locked in for your curtain wall jobs." },
  { website: 'https://aluminiumwindowssydney.com/', email: 'windowsupliers@gmail.com', email1_subject: 'the margin gap most sydney installers carry', email1_body: "you manufacture and install across sydney with 22 years in the trade. supplying through local distributors means longer lead times and thinner margins on every residential job you quote.", email2_subject: 'did this land?', email2_body: "flagged something on supply costs for Aluminium Windows Sydney earlier this week. covers direct-source pricing and the motorised systems most local distributors can't carry.", email3_subject: 're: your minchinbury operation', email3_body: "most fabricators in western sydney we talk to are still quoting through two or three layers of local supply — which adds cost and time to every custom job.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting residential renovations and replacements across sydney, direct-source pricing.", email5_subject: 'last one from me', email5_body: "last ping on supply pricing for Aluminium Windows Sydney. my guess is you haven't replied because: 1. you've locked in existing suppliers and switching feels like admin work." },
  { website: 'https://orionaluminium.com.au/', email: 'info@orionaluminium.com.au', email1_subject: 'something most sydney fabricators miss', email1_body: "you fabricate and install across sydney's residential market. serving custom-made builds with thermal and acoustic specs means you need reliable supply on specialty items.", email2_subject: 'did this land?', email2_body: "left a note with Orion Aluminium about specialty supply gaps recently. covers motorised systems most local suppliers can't source yet.", email3_subject: 're: your residential projects', email3_body: "most fabricators serving sydney's residential market are getting asked about motorised systems but can't source them without long waits or inconsistent stock.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. for custom residential fabricators like Orion Aluminium, having reliable access to motorised systems.", email5_subject: 'last one from me', email5_body: "last ping about motorised supply options for Orion Aluminium. my guess is you haven't replied because: 1. you're locked into existing suppliers and switching feels like hassle." },
  { website: 'https://www.clearstyle.com.au/', email: '', email1_subject: 'something most sutherland shire installers miss', email1_body: "you handle supply and installation across the sutherland shire and eastern suburbs. most installers we speak to in sydney are quoting jobs without access to motorised systems because their suppliers don't stock them.", email2_subject: 'did this land?', email2_body: "dropped a note about motorised systems for CLEARSTYLE a few days back. paul, i know you're juggling installs across the shire and eastern suburbs.", email3_subject: 're: your sutherland shire projects', email3_body: "paul, most installers we work with in sydney mention the same thing — clients ask for motorised louvres or automated stacking sliders, and they either have to say no.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're quoting jobs in the shire where clients want motorised systems.", email5_subject: 'last one from me', email5_body: "last ping paul — i mentioned motorised systems for CLEARSTYLE a couple of weeks back. my guess is you haven't replied because: 1. you're not currently seeing demand." },
  { website: 'https://www.bwwindows.com.au/', email: '', email1_subject: "something most sydney installers can't quote yet", email1_body: "sydney-based installer serving homeowners and builders for 38 years. most local suppliers still can't source motorised systems, even though homeowners upgrading in caringbah and surrounds are asking for them more often.", email2_subject: 'did this land?', email2_body: "B&W Aluminium Windows & Doors — flagged something on motorised systems earlier this week. no hassle if timing's off, but the pricing structure might shift how you quote residential upgrades.", email3_subject: 're: your caringbah projects', email3_body: "most installers working the sutherland shire residential market are quoting standard systems because that's what local suppliers stock. but when a homeowner asks for motorised integration.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting residential upgrades and want access to motorised systems without chasing multiple suppliers.", email5_subject: 'last one from me', email5_body: "last ping for B&W on motorised system pricing. my guess is you haven't replied because: 1. your current supplier mix works fine and switching feels like admin you don't need." },
  { website: 'https://prestigeplus.sydney/', email: '', email1_subject: "something most upvc installers can't offer yet", email1_body: "upvc supplier serving sydney homeowners and renovations. you're focused on double glazed upvc for residential projects across bangor, grasmere, bella vista, and cottage point.", email2_subject: 'did this land?', email2_body: "flagged something on supply consistency for PrestigePlus a few days back. covers motorised systems most sydney upvc suppliers don't stock yet.", email3_subject: 're: your sydney renovation clients', email3_body: "most upvc installers we work with across sydney suburbs like bella vista and cottage point are getting asked about motorised options on residential builds — but local suppliers still don't.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're quoting upvc renovations across sydney and want access to motorised systems.", email5_subject: 'last one from me', email5_body: "last ping on motorised upvc systems for PrestigePlus. my guess is you haven't replied because: 1. you're mid-quote on projects in bangor or cottage point and don't have time." },
  { website: 'https://www.abbeyaluminium.com.au/', email: '', email1_subject: "something most sydney suppliers can't source", email1_body: "you manufacture and supply architectural products across sydney, sutherland shire and wollongong. serving both local builders and homeowners across sydney means you're quoting projects where lead time and product availability can make or break a job.", email2_subject: 'did this land?', email2_body: "left a note with Abbey Aluminium about product availability recently. might be helpful as you scale up across sutherland shire and wollongong projects.", email3_subject: 're: your sutherland shire projects', email3_body: "most manufacturers in your area carry the standard sliding, bi-fold and casement range, but when a builder or homeowner asks for motorised louvres or full-home automation.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if lead time and product range are still pain points for Abbey Aluminium.", email5_subject: 'last one from me', email5_body: "last ping for Abbey Aluminium on the supply side. my guess is you haven't replied because: 1. you've already locked in suppliers and switching feels like unnecessary risk." },
  { website: 'https://simplydoorsandwindows.com.au/', email: '', email1_subject: 'the gap most sydney suppliers have', email1_body: "you supply to homeowners and renovators across sydney at wholesale pricing. from what most installers tell us, the challenge is offering full-home systems when clients ask for motorised options but local stock is patchy.", email2_subject: 'did this land?', email2_body: "left a note with Simply Doors & Windows about motorised system availability recently. worth a look when you get a moment?", email3_subject: 're: your sydney projects', email3_body: "most sydney-based suppliers advertising wholesale pricing still rely on third-party distributors for anything beyond standard configurations, which means homeowners renovating in areas like yours end up waiting.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if quoting motorised full-home systems without chasing stock availability sounds useful.", email5_subject: 'last one from me', email5_body: "last ping for Simply Doors & Windows on motorised system supply. my guess is you haven't replied because: 1. your current suppliers already cover what you need and switching creates more work." },
  { website: 'https://www.twscreens.com.au/', email: '', email1_subject: 'the gap most townsville installers have', email1_body: "security screen specialists servicing townsville and the burdekin shire you're focused on crimsafe and stainless steel mesh for homes across north queensland.", email2_subject: 'did this land?', email2_body: "left a note with Townsville Windows and Screens about product range gaps recently. worth a look when you get a moment?", email3_subject: 'something about your burdekin projects', email3_body: "homes across townsville, kirwan and north ward need security and airflow year-round. most installers in your area are still limited to what local suppliers stock.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're quoting homes across garbutt and idalia and want access to motorised systems.", email5_subject: 'last one from me', email5_body: "last ping about product range gaps for Townsville Windows and Screens. my guess is you haven't replied because: 1. you're locked in with existing crimsafe suppliers and switching feels like too much hassle." },
  { website: 'https://thewindowfactory.com.au/', email: '', email1_subject: "something most installers can't source yet", email1_body: "you install across shopfronts, large builds, and residential projects. quoting on commercial projects means you need stock consistency and reliable lead times.", email2_subject: 'did this land?', email2_body: "left a note with The Window Factory about stock consistency on commercial projects recently. covers motorised systems most au suppliers don't carry.", email3_subject: 're: your commercial projects', email3_body: "most installers serving both shopfronts and large builds end up juggling multiple suppliers to cover their range — especially when developers start asking for automated systems.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if keeping one supplier for both standard commercial stock and motorised systems matters.", email5_subject: 'last one from me', email5_body: "last ping for The Window Factory on stock consistency for your commercial builds. my guess is you haven't replied because: 1. you've already got reliable suppliers and don't see a reason to change." },
  { website: 'https://www.glasssupplies.com.au/', email: 'reception@glasssupplies.com.au' },
  { website: 'http://www.theglenorchytipshop.com.au/', email: 'ict_support@theglenorchytipshop.com.au' },
  { website: 'https://millicentwindowsanddoors.net.au/', email: 'millwind@bigpond.com', email1_subject: 'the one thing most limestone coast suppliers miss', email1_body: "family owned manufacturer covering limestone coast and southwest victoria. you're building locally in millicent and supplying vantage, elevate and thermalheart across sa and parts of victoria.", email2_subject: 'did this land?', email2_body: "flagged something on supply consistency for millicent windows and doors earlier this week. covers motorised full-home systems most regional manufacturers still have a gap on.", email3_subject: 're: your millicent operations', email3_body: "most family owned manufacturers in regional sa we work with hit the same wall — they can quote vantage and elevate all day, but when a builder or homeowner asks for motorised louvres.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting jobs across limestone coast and losing margin to product gaps on motorised systems.", email5_subject: 'last one from me', email5_body: "last ping on motorised supply for millicent windows and doors. my guess is you haven't replied because: 1. you're flat out with current vantage and elevate orders." },
  { website: 'https://www.australw.com.au/', email: 'sales@australw.com.au', email1_subject: "something most campbellfield suppliers can't get", email1_body: "you build residential awning, casement, bi-fold and sliding systems across melbourne. over thirty years means you've likely built strong relationships with your residential builder clients, but lead times on specialty items still push timelines out.", email2_subject: 'still worth a look?', email2_body: "left a note with Austral Aluminium Products about lead times on specialty systems recently. worth a look when you get a moment?", email3_subject: 're: your residential builder clients', email3_body: "most residential fabricators in campbellfield and surrounds we speak to hit the same wall — builders are asking for motorised window and door systems on mid to high-end homes.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting residential projects where motorised systems come up and you'd like direct-source pricing.", email5_subject: 'last one from me', email5_body: "last ping on direct-source supply for Austral Aluminium Products — specifically around motorised systems that your residential clients are starting to spec." },
  { website: 'https://www.legg.com.au/', email: 'admin@legg.com.au' },
  { website: 'http://avanti.com.au/', email: 'mail@avanti.com.au', email1_subject: "something most perth suppliers can't source", email1_body: "custom fabricator serving the WA coastline with 40 years behind you. you're delivering high-end curved windows and frameless panoramic doors, but sourcing complexity can still slow down lead times on specialty work.", email2_subject: 'did this land?', email2_body: "flagged something on supply complexity for Avanti Glass & Aluminium earlier this week. still relevant if you're quoting custom coastal projects where lead time matters.", email3_subject: 're: your WA coastline work', email3_body: "most fabricators we work with along the WA coast mention the same thing: clients are asking for motorised systems on beachfront builds, but local supply options are either limited or involve long waits.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. for a WA fabricator handling custom coastal projects, having direct access to motorised systems.", email5_subject: 'last one from me', email5_body: "last ping on supply access for Avanti Glass & Aluminium and those coastal custom builds. my guess is you haven't replied because: 1. you've already got reliable suppliers." },
  { website: 'http://www.ledaaluminium.com.au/', email: 'info@ledaaluminium.com.au', email1_subject: 'the margin gap nobody talks about', email1_body: "you fabricate and install across sydney's western suburbs — parramatta, blacktown, penrith. when you're quoting on apartments and commercial builds, your lead times are locked to whoever's stocking the frames.", email2_subject: 'still worth a look?', email2_body: "dropped a note about supply control for Leda Aluminium a few days back — specifically on apartments and commercial work across western sydney. worth a look when you get a moment?", email3_subject: 're: your parramatta projects', email3_body: "most fabricators working high-rise apartments in parramatta and penrith are still relying on local distributors who can't carry motorised louvre or full-home automation.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if lead time control matters on your apartment builds, i can send across our catalogue.", email5_subject: 'last one from me', email5_body: "last ping on direct-source supply for Leda Aluminium — specifically around apartment and commercial jobs. my guess is you haven't replied because: 1. you've already got suppliers locked in." },
  { website: 'http://www.open-windows.com.au/', email: 'quotes@open-windows.com.au', email1_subject: 'the gap most perth suppliers still have', email1_body: "you supply premium aluminium products across perth with double glazing and custom installs. you're likely quoting competitively but watching margin get tighter on every job.", email2_subject: 'did this land?', email2_body: "left a note with Open Windows & Doors about tighter quoting margin recently. no pressure if timing isn't right. worth a look when you get a moment?", email3_subject: 'something i noticed about perth', email3_body: "most perth suppliers offering double glazing and custom residential installs are great at design and service but get stuck waiting on stock or paying distributor markup.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if tighter margin on competitive perth quotes is still an issue.", email5_subject: 'last one from me', email5_body: "last ping on supply and margin for Open Windows & Doors. my guess is you haven't replied because: 1. you've already got solid supplier relationships and switching feels like unnecessary risk." },
  { website: 'http://www.nulookwindows.com.au/', email: 'info@nulookwindows.com.au', email1_subject: 'the gap most perth suppliers have', email1_body: "installer serving residential and commercial builds across Perth and WA. you're covering sliding, awning, bifolds, security screens — but most perth suppliers still can't source motorised full-home systems.", email2_subject: 'still relevant?', email2_body: "flagged something on motorised supply gaps for Nu Look Windows earlier this week. guessing inbox got buried — happens. catalogue shows full range with lead times and trade pricing.", email3_subject: 're: your perth client base', email3_body: "most installers covering both residential renovations and commercial work in perth hit the same wall — clients asking for motorised awning or sliding systems, but local supply either doesn't stock them.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read Nu Look Windows — if motorised supply or tighter lead times matter for your perth projects.", email5_subject: 'last one from me', email5_body: "last ping on motorised systems and direct pricing for Nu Look Windows. my guess is you haven't replied because: 1. you're flat out quoting or managing installs and this just wasn't priority." },
  { website: 'https://www.pattersonglassqld.com.au/', email: 'glass@pattersonglass.com.au', email1_subject: 'the one thing most gold coast suppliers miss', email1_body: "family-owned manufacturer servicing gold coast commercial and residential builds for over 50 years. you're known for architectural facades and high-end projects across the region.", email2_subject: 'did this land?', email2_body: "left a note with Patterson Glass about supply gaps on architectural builds earlier this week. could be relevant given the type of work you're doing on the gold coast.", email3_subject: 're: your gold coast projects', email3_body: "architects and designers on the gold coast are increasingly speccing motorised systems into mid-to-high-end residential and commercial builds. most suppliers still don't stock them.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read given the architectural and commercial work Patterson Glass handles, a catalogue showing motorised systems.", email5_subject: 'last one from me', email5_body: "last ping on supply options for Patterson Glass on the motorised systems gap. my guess is you haven't replied because: 1. you've already got suppliers locked in and switching isn't worth the hassle." },
  { website: 'http://www.manlywindows.com.au/', email: 'admin@manlywindows.com.au' },
  { website: 'http://www.windowwarehouseqld.com.au/', email: 'sales@windowwarehouseqld.com.au', email1_subject: 'the margin gap most brisbane suppliers face', email1_body: "you supply and install across brisbane metro with stock ready to go. most suppliers in your position end up with thin margins because they're limited to what local distributors carry at markup.", email2_subject: 'did this land?', email2_body: "dropped a note about margin pressure for Window Warehouse a few days back. not sure if it hit your inbox or got buried. worth a look when you get a moment?", email3_subject: 're: your brisbane metro projects', email3_body: "most installers we work with in brisbane metro run into the same issue — they can supply and install everything except motorised systems because local distributors don't stock them.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting jobs where margin matters or clients are asking for motorised systems.", email5_subject: 'last one from me', email5_body: "last ping about direct-source supply for Window Warehouse. my guess is you haven't replied because: 1. you've already got reliable suppliers and the margin works fine." },
  { website: 'https://www.rnrwindowsdoors.com.au/', email: 'sales@rnrglass.com.au' },
  { website: 'https://www.shapealuminium.net.au/', email: '', email1_subject: 'the one thing most pool fencers miss', email1_body: "you supply pool fencing panels and safety hardware across australia. you're stocking magna latch kits and polaris hinges but relying on local distributors for core panel supply.", email2_subject: 'still relevant for you?', email2_body: "flagged something about supply costs for Shape Aluminium earlier this week. motorised systems are hard to source locally and your current panel pricing likely has a distributor margin baked in.", email3_subject: 're: your pool safety hardware range', email3_body: "most pool fencing suppliers we work with stock the accessories — magna latch, polaris hinges, lockwood handles — but still buy panels and gate frames through a distributor.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. you're selling pool panels at $97.89 retail — direct-source pricing on those same specs would give you more margin.", email5_subject: 'last one from me', email5_body: "last ping about supply pricing for Shape Aluminium. my guess is you haven't replied because: 1. your current distributor relationship works fine and switching feels like added complexity." },
  { website: 'https://colonialwarehouse.com.au/', email: 'sales@colwh.com.au', email1_subject: 'the one thing timber specialists skip', email1_body: "sixth-generation timber door and window makers in Brisbane premium timber is your specialty, but homeowners calling Colonial Warehouse are starting to ask for one thing you can't currently supply.", email2_subject: 'did this land?', email2_body: "dropped a note about supply gaps for Colonial Warehouse a few days back. motorised systems are the one category most timber businesses don't carry.", email3_subject: 'something i noticed about Brisbane builds', email3_body: "builders doing french doors and bifolds in Brisbane are mixing timber and aluminium on the same project more than ever. they want consistency across suppliers but most can only do one material well.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if Colonial Warehouse ever gets asked for motorised systems or wants to expand beyond timber.", email5_subject: 'last one from me', email5_body: "last ping about supply options for Colonial Warehouse my guess is you haven't replied because: 1. timber is your core business and you're not actively looking to add aluminium." },
  { website: 'http://www.windowmakers.com.au/', email: 'sales@windowmakers.com.au', email1_subject: 'the gap most gold coast fabricators have', email1_body: "fabricator specialists to Southern Gold Coast and Northern Rivers. you're carrying Vantage, Elevate and ThermalHEART — all solid lines for traditional installs. but when a builder specs motorised, you're likely referring it out or passing.", email2_subject: 'still worth a look?', email2_body: "Window Makers — flagged something about motorised supply gaps earlier this week. not sure if it landed or just got buried. worth a look when you get a moment?", email3_subject: 're: your northern rivers projects', email3_body: "most fabricators in your area are set up beautifully for casement, sliding, and bi-fold work — but the moment a builder asks for motorised awnings or full-home automation, the job either gets referred out.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if motorised supply is something you'd like to add to your range for Southern Gold Coast.", email5_subject: 'last one from me', email5_body: "last ping about motorised supply for Window Makers. my guess is you haven't replied because: 1. you're fully booked and not taking on new product lines right now." },
  { website: 'https://www.adshutters.com.au/', email: 'sales@adshutters.com.au', email1_subject: 'the one thing most sydney installers miss', email1_body: "you supply and install roller shutters across sydney and brisbane. serving both residential and commercial clients means you need consistent stock and reliable turnaround.", email2_subject: 'did this land?', email2_body: "dropped a note about supply consistency for AdShutters a few days back. we work with installers in sydney and brisbane who need motorised systems their current suppliers don't carry.", email3_subject: 're: your sydney and brisbane work', email3_body: "most roller shutter installers we speak to across sydney and brisbane are getting requests for motorised window systems but don't have a supplier who stocks them locally.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if you're quoting jobs across sydney and brisbane and need a backup supplier for motorised systems.", email5_subject: 'last one from me', email5_body: "last ping regarding AdShutters and your supply chain for motorised systems. my guess is you haven't replied because: 1. you already have suppliers locked in and switching isn't worth the hassle." },
  { website: 'https://selectwindows.com.au/', email: 'sales@selectwindows.com.au', email1_subject: "something most sydney installers can't offer yet", email1_body: "installing across sydney since 2007, serving residential and commercial clients. you're covering everything from apartment blocks to office spaces, balcony replacements to full commercial builds.", email2_subject: 'did this land?', email2_body: "flagged something about product gaps for Select Window Installations earlier this week. motorised full-home systems are the one category most sydney installers still refer out.", email3_subject: 're: your sydney wide projects', email3_body: "you've been covering residential homes, apartment blocks, and commercial office spaces across sydney for nearly 20 years. the installers we work with say the same thing — they're quoting more jobs where motorised systems come up.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're quoting jobs where motorised full-home systems come up and you'd like to see our catalogue.", email5_subject: 'last one from me', email5_body: "last ping on motorised system supply for Select Window Installations. my guess is you haven't replied because: 1. you're not seeing enough demand for motorised systems to justify a new supplier relationship." },
  { website: 'http://www.easywindows.com.au/', email: 'sales@easywindows.com.au', email1_subject: 'the product gap most sydney suppliers have', email1_body: "upvc specialists serving sydney and the northern beaches since 2004. you're running german profiles with double and triple glazing across residential projects — but lead times from europe can stretch your turnaround.", email2_subject: 'did this land?', email2_body: "left a note with Easy Windows about lead time pressure on european profiles recently. motorised full-home systems are the one category most nsw suppliers still have a gap on.", email3_subject: 're: your brookvale operation', email3_body: "you manufacture locally in brookvale which gives you control — but you're still tied to aluplast profiles shipped from overseas for your upvc range. most sydney installers running european upvc face the same tension.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if lead times on your upvc profiles are creating quoting delays for jobs across sydney and nsw.", email5_subject: 'last one from me', email5_body: "last ping on supply options for Easy Windows and lead time pressure on european profiles. my guess is you haven't replied because: 1. your aluplast relationship is locked in." },
  { website: 'http://www.donalco.com.au/', email: 'admin@donalco.com.au', email1_subject: "something most brookvale suppliers can't source", email1_body: "custom commercial grade fabricator on sydney's northern beaches. you're manufacturing everything in brookvale, which means control over quality but longer turnaround when demand spikes.", email2_subject: 'did this land?', email2_body: "left a note with Donalco about volume project turnaround earlier this week. worth a look when you get a moment?", email3_subject: 're: your brookvale projects', email3_body: "most sydney fabricators we work with hit the same wall — custom commercial work needs fast quoting to win jobs, but in-house manufacturing stretches lead times when multiple projects overlap.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if faster quoting on commercial projects sounds useful, i can send across our catalogue.", email5_subject: 'last one from me', email5_body: "final note for Donalco on volume project turnaround. my guess is you haven't replied because: 1. you've already got reliable suppliers and turnaround isn't currently an issue." },
  { website: 'https://wizardwindows.com.au/', email: 'sales@wizardwindows.com.au' },
  { website: 'https://venwindows.com.au/', email: 'sales@venwindows.com.au' },
  { website: 'https://eastcoastaluminium.com.au/', email: '', email1_subject: 'the gap most ballina installers overlook', email1_body: "security screens and glass replacements across ballina and the northern rivers. you cover security doors, shower screens and glass repairs but sourcing takes longer than it should.", email2_subject: 'did this land?', email2_body: "dropped a note about supply reliability for Eastcoast Aluminium & Glass a few days back. might be useful if you're looking at tightening up lead times on your northern rivers projects.", email3_subject: 're: your northern rivers work', email3_body: "most installers in ballina we talk to mention the same thing — they lose quotes because they can't commit to install dates until stock arrives. you're covering security screens, shower screens and glass replacements.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if lead times on security screens and glass jobs are eating into your schedule.", email5_subject: 'last one from me', email5_body: "last ping for Eastcoast Aluminium & Glass on supply reliability. my guess is you haven't replied because: 1. current suppliers are working fine and you're not actively looking to change anything." },
  { website: 'http://suburban-windows.com/', email: '', email1_subject: 'the gap most arundel suppliers have', email1_body: "residential installer servicing the gold coast with a full product range. you're covering sliding, awning, bi-fold, double hung, hinged, french, stacking, double glazed, and thermally broken systems.", email2_subject: 'still worth checking?', email2_body: "left a note with Suburban Windows about product gaps earlier this week. most gold coast installers we work with didn't realise how accessible motorised systems have become until they saw the pricing.", email3_subject: 're: your newheath drive operation', email3_body: "most residential installers on the gold coast are competing on the same product categories — sliding, bi-fold, awning, double hung. the ones picking up higher-margin jobs are the ones who can offer what their competitors can't spec yet.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're looking to expand what Suburban Windows can offer residential clients across arundel and the gold coast.", email5_subject: 'last one from me', email5_body: "last ping about expanding what Suburban Windows can offer without adding supply headaches. my guess is you haven't replied because: 1. you're mid-quote season and this feels like one more thing to evaluate." },
  { website: 'https://www.betaview.com.au/', email: 'sales@betaview.com.au', email1_subject: 'something most sydney suppliers miss', email1_body: "you specialise in residential installations across Sydney. you're already covering sliding, bifold, stacking — full range locally manufactured.", email2_subject: 'did this land?', email2_body: "flagged something about motorised supply gaps for BetaView earlier this week. worth a look when you get a moment?", email3_subject: 're: your sydney residential projects', email3_body: "most residential installers in Sydney we've worked with say the same thing — they get asked about motorised options on quotes, but their current suppliers either don't stock them or quote long lead times.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if motorised supply is a gap in your current range, i can send across our catalogue.", email5_subject: 'last one from me', email5_body: "last ping on motorised supply for BetaView. my guess is you haven't replied because: 1. your current supplier already covers motorised and lead times are fine." },
  { website: 'http://www.mrwindows.com.au/', email: 'info@mrwindows.com.au', email1_subject: "the gap most hardware suppliers can't fill", email1_body: "you stock replacement parts for sliding, security and bifold systems across australia. given your range spans bradnams, stegbar and multiple other brands, keeping consistent stock on every part must be a constant chase.", email2_subject: 'did this land?', email2_body: "flagged something about supply consistency for Mr Windows AU earlier this week. covers motorised systems and direct-source pricing. worth a look when you get a moment?", email3_subject: 're: your replacement parts business', email3_body: "most hardware suppliers we speak to in australia are great at servicing existing systems but can't offer complete new installs when customers ask. you stock parts for bradnams, stegbar and others.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. if keeping stock on every replacement part is already stretched, adding a direct supplier for motorised full-home systems.", email5_subject: 'last one from me', email5_body: "final note for Mr Windows AU about filling the motorised system gap. my guess is you haven't replied because: 1. you're focused on replacement parts and not sure if full systems fit your model." },
  { website: 'http://www.polytron.au/', email: 'admin@polytron.au', email1_subject: 'the one category most suppliers miss', email1_body: "you manufacture switchable glass and structural solutions across australia. most projects you complete from homes to hospitals rely on glass that adapts to privacy needs — but sourcing compatible framing that supports motorised operation can slow things down.", email2_subject: 'still worth a look?', email2_body: "flagged something on motorised framing compatibility for Polytron earlier this week. most switchable glass projects now need motorised window and door systems to complete the smart building spec.", email3_subject: 'something about qld projects', email3_body: "you manufacture in qld and ship australia wide — which means your clients expect the same speed and reliability from every component in their build. the challenge we keep hearing is that switchable glass arrives on time.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read Polytron — if motorised framing that ships australia wide and matches your switchable glass timelines.", email5_subject: 'last one from me', email5_body: "last ping on motorised framing supply for Polytron. my guess is you haven't replied because: 1. you already have reliable suppliers for framing and don't need another contact right now." },
  { website: 'https://saaw.com.au/', email: 'info@saaw.com.au' },
  { website: 'http://www.youngglass.com.au/', email: 'sales@youngglass.com.au' },
  { website: 'https://www.dortec.com.au/', email: 'sales@dortec.com.au' },
  { website: 'https://byronglass.com.au/', email: 'sales@byronglass.com.au' },
  { website: 'http://taberners.com.au/', email: 'windows@taberners.com.au' },
  { website: 'http://crystalwindowsanddoors.com.au/', email: 'sales@thejjdgroup.com.au' },
  { website: 'https://almet.com.au/', email: 'sales@almet.com.au', email1_subject: 'the margin gap nobody talks about', email1_body: "you supply partition and shopfront systems across queensland. you're juggling multiple suppliers just to cover your full range — partition, doors, shopfronts, facades.", email2_subject: 'still worth a look?', email2_body: "dropped a note about supply consolidation for Almet Aluminium a few days back. covers partition, door, and facade systems — plus the motorised range most gold coast suppliers don't carry.", email3_subject: 're: your gold coast projects', email3_body: "most partition suppliers on the gold coast are still pushing 8-10 week lead times and charging a premium because they're middlemen stacking margin. you've built your range around kit form systems.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. for partition suppliers expanding their door and facade range, we have full catalogue and certs covering double glazed systems.", email5_subject: 'last one from me', email5_body: "last ping on direct-source supply for Almet Aluminium — specifically around consolidating your partition, door, and facade range under one supplier. my guess is you haven't replied because: 1. your current suppliers are good enough." },
  { website: 'http://www.allteck.com.au/', email: 'sales@allteck.com.au' },
  { website: 'http://www.spscreens.com.au/', email: 'peta@spscreens.com.au', email1_subject: "the supply gap most installers don't see", email1_body: "security screens and retractable fly screens across australia. you're covering everything from hinged security screens to wide retractable openings and aluminium slat fencing.", email2_subject: 'did this land?', email2_body: "left a note with SP Screens about supply consistency recently. not sure if it hit your inbox or got buried. either way, no stress — worth a look when you get a moment?", email3_subject: 'something about your retractable range', email3_body: "you're covering retractable screens for wide door openings — that's a product category where delivery delays hit hardest because clients are waiting to access entire living areas.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if you're quoting retractable screens or security installs and want consistent stock without the usual wait.", email5_subject: 'last one from me', email5_body: "last ping on supply options for SP Screens. my guess is you haven't replied because: 1. you've already got suppliers locked in and switching feels like extra work right now." },
  { website: 'https://sgaaws.com.au/', email: 'sales@sgaaws.com.au', email1_subject: "something most coffs fabricators can't source", email1_body: "local fabricator serving coffs harbour and surrounding regions since 1978. you're supplying residential and commercial projects across emerald beach, fernmount, and yaringa — traditional manual systems that work well for most builds.", email2_subject: 'did this land?', email2_body: "left a note with SGA about motorised system supply gaps recently. not sure if it hit your inbox or got buried. worth a look when you get a moment?", email3_subject: 're: your coffs harbour projects', email3_body: "most fabricators in regional NSW are set up perfectly for standard residential and commercial work — emerald beach, fernmount, the usual build types around coffs harbour.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if motorised systems ever come up on quotes for emerald beach or yaringa projects.", email5_subject: 'last one from me', email5_body: "last ping about motorised system supply for SGA. my guess is you haven't replied because: 1. you're not quoting many projects right now that need motorised systems." },
  { website: 'https://luxviewwindows.com.au/', email: 'info@luxviewwindows.com.au', email1_subject: 'something most fabricators are missing right now', email1_body: "you fabricate and install custom aluminium solutions across residential and commercial projects. serving both sectors means you're quoting against competitors who either go cheap or can't deliver on time.", email2_subject: 'did this land?', email2_body: "left a note with Lux View Windows about lead time and quoting pressure recently. not sure if it hit your inbox or got buried. worth a look when you get a moment?", email3_subject: 're: your residential and commercial work', email3_body: "most fabricators running both residential and commercial projects face the same issue — residential clients want faster turnaround, commercial wants tighter pricing, and local suppliers can't deliver both consistently.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. for fabricators like Lux View Windows managing custom residential and commercial builds.", email5_subject: 'last one from me', email5_body: "last ping about supply reliability and quoting pressure for Lux View Windows. my guess is you haven't replied because: 1. you've already got suppliers locked in and switching feels like extra work right now." },
  { website: 'https://decoview.com.au/', email: 'sales@decoview.com.au' },
  { website: 'https://www.cedaraluminium.com.au/', email: 'admin@cedaraluminium.com.au', email1_subject: 'the margin gap nobody talks about', email1_body: "you supply custom framing and install across Sydney you're serving everyone from small residential jobs to commercial builders with discounted pricing, which means quoting tight and keeping stock consistent matters.", email2_subject: 'still worth a look?', email2_body: "flagged something on direct pricing for Cedar Aluminium earlier this week — not sure if it landed or got buried. covers motorised systems most AU suppliers don't carry.", email3_subject: 're: your wetherill park projects', email3_body: "most Sydney framers we work with say the same thing — they're quoting residential and commercial jobs tight, but local suppliers either don't stock motorised systems or the lead times blow out the schedule.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read we supply motorised full-home systems direct to installers like Cedar Aluminium.", email5_subject: 'last one from me', email5_body: "last ping on direct pricing for Cedar Aluminium — not sure if this landed or just wasn't the right time. my guess is you haven't replied because: 1. you've already got solid supplier relationships." },
  { website: 'http://www.westal.com.au/', email: 'canberra@westal.com.au', email1_subject: 'the gap most regional nsw suppliers have', email1_body: "manufacturer supplying across orange, bathurst, newcastle and canberra servicing residential and commercial across such a wide territory means juggling lead times and product availability.", email2_subject: 'did this land?', email2_body: "dropped a note about motorised systems for Westal a few days back. no pressure, just thought it might fill a gap in your current range. worth a look when you get a moment?", email3_subject: 'something about your canberra market', email3_body: "builders working across orange to canberra are asking for motorised systems more frequently now, especially on new builds and architectural projects. most regional manufacturers we speak to either can't source them.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read happy to send across our catalogue and cert list so you can see what motorised options suit residential.", email5_subject: 'last one from me', email5_body: "last ping on motorised systems for Westal and your nsw territory. my guess is you haven't replied because: 1. you're locked into existing suppliers and switching feels like too much work right now." },
  { website: 'https://seabreezewindows.com.au/', email: 'info@seabreezewindows.com.au', email1_subject: 'something most northern beaches suppliers miss', email1_body: "specialist supply and install covering the northern beaches and surrounds. you partner with multiple manufacturers to offer variety, but that means coordinating stock across suppliers for each job.", email2_subject: 'did this land?', email2_body: "left a note with Seabreeze Windows about coordinating stock across multiple suppliers recently. not sure if it hit your inbox or got buried. worth a look when you get a moment?", email3_subject: 're: your brookvale showroom', email3_body: "most northern beaches installers we talk to run into the same issue — they offer range by partnering with multiple suppliers, but it means chasing stock from different places and quoting off different rate cards.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if coordinating supply across multiple manufacturers is eating into your quote turnaround time.", email5_subject: 'last one from me', email5_body: "last ping about supply consolidation for Seabreeze Windows. my guess is you haven't replied because: 1. your current supplier relationships are locked in and working fine for now." },
  { website: 'http://akaluminiumwindowsandoors.com.au/', email: 'adam@akaluminiumwindowsanddoors.info', email1_subject: 'the margin gap most installers miss', email1_body: "you install across cherrybrook, hornsby and cranebrook from what i can see. tight margins on every quote means chasing volume just to stay profitable.", email2_subject: 'did this land?', email2_body: "left a note with AK Aluminium Windows and Doors about tighter margins on residential installs recently. no stress if timing isn't right — just flagging in case it got buried.", email3_subject: 're: your hornsby projects', email3_body: "most installers we work with in sydney's north west are quoting the same three local suppliers — which means everyone's working with identical pricing and lead times. that makes it hard to win jobs without cutting your own margin.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if tighter margins are eating into what you take home on residential installs.", email5_subject: 'last one from me', email5_body: "last ping on direct pricing for AK Aluminium Windows and Doors. my guess is you haven't replied because: 1. you've already got supplier relationships locked in and switching feels like effort." },
  { website: 'https://www.rylock.com.au/', email: 'careers@rylock.com.au', email1_subject: 'the gap most melbourne showrooms have', email1_body: "custom double glazed manufacturer with showrooms across melbourne, sydney, adelaide and hobart. you're covering everything from urban to coastal builds, but lead times and spec consistency likely slow down your larger projects.", email2_subject: 'still worth a look?', email2_body: "flagged something on lead times for Rylock earlier this week. no pressure, just circling back in case it got buried. worth a look when you get a moment?", email3_subject: 're: your melbourne showroom projects', email3_body: "most custom manufacturers we speak to in melbourne and sydney run into the same issue — clients are specifying motorised systems on architectural builds, but the local supply chain can't deliver them without adding weeks.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if lead times on custom specs are slowing down your melbourne, sydney, adelaide or hobart projects.", email5_subject: 'last one from me', email5_body: "last ping on motorised systems and lead times for Rylock. my guess is you haven't replied because: 1. your current supply chain is working fine and you're not looking to change anything." },
  { website: 'https://windowsaluminium.com.au/', email: 'aluminium.dw1@gmail.com', email1_subject: 'something athir might want to check', email1_body: "installation and repair work across sydney takes experience and consistency. you've built 15+ years of hands-on craftsmanship — but sourcing can still eat into job margins when lead times stretch or pricing fluctuates.", email2_subject: 'did this land?', email2_body: "left a note with Aluminium Doors & Windows 1 about tighter quoting and lead time control recently. worth a look when you get a moment?", email3_subject: 're: your sydney install work', email3_body: "most sydney installers we work with are quoting jobs weeks out because they're waiting on stock from local suppliers who are waiting on their suppliers. you've built a reputation on being on time.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read if tighter job margins and reliable stock timelines matter to your install work.", email5_subject: 'last one from me', email5_body: "last ping for Aluminium Doors & Windows 1 on direct pricing and stock reliability. my guess is you haven't replied because: 1. you've already got suppliers locked in and switching feels like unnecessary risk." },
  { website: 'https://www.aswindowsdoors.com.au/', email: 'admin@aswindowsdoors.com.au', email1_subject: 'something most sydney fabricators miss', email1_body: "you manufacture and fit custom aluminium across sydney. you're serving residential and commercial projects with made-to-size products that meet australian standards.", email2_subject: 'did this land?', email2_body: "left a note with AS Aluminium Windows & Doors about supply consistency recently. covers motorised full-home systems that most local suppliers don't stock.", email3_subject: 're: your sydney projects', email3_body: "most fabricators we talk to across sydney are quoting residential and commercial work but turning down jobs that need motorised systems because their current suppliers can't source them reliably.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy so this will only take you 60 seconds to read when you're quoting residential and commercial projects across sydney, having access to motorised systems.", email5_subject: 'last one from me', email5_body: "last ping for AS Aluminium Windows & Doors on expanding what you can quote for. my guess is you haven't replied because: 1. you're flat out with current projects and haven't had time." },
  { website: 'http://www.windowsanddoorssydney.com.au/', email: 'ally@gemwindowsanddoors.com.au', email1_subject: 'the one thing most sydney suppliers miss', email1_body: "you supply direct to public across mascot, castle hill, minto and kingswood. with 55,000 orders filled, keeping stock and quoting fast are key to staying ahead of local competitors.", email2_subject: 'did this land?', email2_body: "flagged something on motorised stock availability for GEM Windows & Doors earlier this week. not sure if it hit your inbox. worth a look when you get a moment?", email3_subject: 're: your four sydney showrooms', email3_body: "most suppliers with your kind of retail footprint across mascot, castle hill, minto and kingswood end up losing quotes when customers ask about automation, because local stock just isn't there.", email4_subject: '60 seconds, i promise', email4_body: "i know you are incredibly busy. so this will only take you 60 seconds to read. given how fast you turn quotes and how much stock you keep at prestons.", email5_subject: 'last one from me', email5_body: "last ping on motorised supply for GEM Windows & Doors. my guess is you haven't replied because: 1. you're not seeing enough demand for motorised yet to justify adding a new supplier." },
  { website: 'https://sydneyhcaluminium.com.au/', email: 'info@sydneyhcaluminium.com.au', email1_subject: 'what if your aluminium supplier costs you jobs?', email1_body: "installers covering sydney's northwest with 20 years on the books face this constantly. chasing down suppliers for specialty products eats up time you could spend on site.", email2_subject: 'motorised systems for AK Aluminium', email2_body: "sent over a note on motorised window systems and direct-source pricing for AK Aluminium a couple of days ago. worth a look when you get a moment?", email3_subject: "specialty stock in sydney's northwest", email3_body: "most installers we work with in Cherrybrook and Hornsby end up chasing multiple suppliers to cover their full range." },
];

async function importHistoricalLeads() {
  console.log(`[Import] 开始导入 ${historicalLeads.length} 条历史数据（窗门供应商）...`);

  const { data: searchRecord, error: searchErr } = await supabase
    .from('search_history')
    .insert({
      query: 'historical_import_windows_doors',
      location: 'Australia',
      max_results: historicalLeads.length,
      total_scraped: historicalLeads.length,
      total_qualified: historicalLeads.length,
    })
    .select()
    .single();

  if (searchErr) {
    console.error('[Import] 创建 search_history 失败:', searchErr);
    process.exit(1);
  }

  const searchId = searchRecord.id;
  console.log(`[Import] search_history ID: ${searchId}`);

  const records = historicalLeads
    .filter(l => l.email || l.website)
    .map(l => ({
      search_id:        searchId,
      email:            l.email || null,
      website:          l.website || null,
      website_domain:   l.website ? extractDomain(l.website) : null,
      company_name:     companyFromDomain(l.website),
      email1_subject:   l.email1_subject || null,
      email1_body:      l.email1_body    || null,
      email2_subject:   l.email2_subject || null,
      email2_body:      l.email2_body    || null,
      email3_subject:   l.email3_subject || null,
      email3_body:      l.email3_body    || null,
      email4_subject:   l.email4_subject || null,
      email4_body:      l.email4_body    || null,
      email5_subject:   l.email5_subject || null,
      email5_body:      l.email5_body    || null,
      created_at:       new Date().toISOString(),
    }));

  let { error } = await supabase.from('leads').insert(records);

  // Fallback: strip columns that don't exist yet in the schema
  if (error?.message?.includes('column') || error?.message?.includes('website_domain')) {
    const missing = error.message.match(/'([^']+)'/)?.[1] || 'unknown';
    console.warn(`[Import] 列 "${missing}" 不存在，请先执行 SQL migration，当前跳过可选字段重试...`);
    const fallback = records.map(({ website_domain, email1_subject, email1_body, email2_subject, email2_body, email3_subject, email3_body, email4_subject, email4_body, email5_subject, email5_body, ...core }) => core);
    ({ error } = await supabase.from('leads').insert(fallback));
  }

  if (error) {
    console.error('[Import] 插入失败:', error);
    process.exit(1);
  } else {
    console.log(`[Import] ✅ 成功导入 ${records.length} 条历史数据（窗门供应商）`);
  }
}

importHistoricalLeads();
